draw_set_halign(fa_center)
draw_set_font(fnt_title)
draw_text(obj_title.x,obj_title.y,"<insert quirky title>")
draw_set_font(fnt_subtitle)
draw_text(obj_title.x,obj_title.y+80,"BY OLIVER MALINARIC & RASMUS LOBERG")